id: I4E68E844
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:37:17+00:00'
last_modified: '2022-06-08T02:14:27.948101+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20114
  title: རོགས་འཐེན་རྡོ་རྗེའི་ཚེ་མདུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E7D6:
      image_group_id: I1KG22765
      title: ''
      total_pages: 362
      order: 1
      base_file: E7D6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
