id: P004602
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20114
  title: རོགས་འཐེན་རྡོ་རྗེའི་ཚེ་མདུད།
  author: ''
  volumes:
    99881ba0dc084d3ba0a9c8f7d9e4eddf:
      image_group_id: I1KG22765
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
